### PR TITLE
Change/fix UI feedback for some commands

### LINKED ISSUE #176: Improve UI text

### PR DESCRIPTION
**Pull request by snss231**
Make some improvements to UI feedback e.g. MESSAGE_USAGE

fixes #176

### CODE REVIEW

**Comment by snss231** [comment]
fixes #176

File: src/main/java/seedu/address/logic/commands/AddTaskCommand.java [hunk 1]
```diff
@@ -24,19 +24,19 @@
...
+            + " [" + PREFIX_LINK + "LINK] "
+            + " [" + PREFIX_RECURRING + "PERIOD RECURRENCE]\n"
             + "Example: " + "addt" + " "
             + PREFIX_TASKNAME + "John Doe "
             + PREFIX_DATETIME + "25-12-2022 1800 "
-            + PREFIX_TAG + "CS2103T"
-            + " [" + PREFIX_LINK + "https://...]"
-            + " [" + PREFIX_RECURRING + "5 5]\n"
+            + PREFIX_TAG + "CS2103T "
+            + PREFIX_LINK + "https://[...] "
```
Comment (brian16600) [inline src/main/java/seedu/address/logic/commands/AddTaskCommand.java:38]: Since this is an example we shouldn't put the [ ] brackets? Just leave it as https://... else is it possible they get confused thinking its optional

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 2]
```diff
@@ -18,15 +18,13 @@
 public class ViewCommand extends Command {
     public static final String COMMAND_WORD = "view";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Display all relevant contacts under a task "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Display all contacts assigned the task identified "
```
Comment (brian16600) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java:21]: Perhaps it should be "assigned to the task identified"? Maybe missing a "to"

**Comment by brian16600** [comment]
Mostly LGTM, just minor changes. Thanks for updating the language

File: src/main/java/seedu/address/logic/commands/AddTaskCommand.java [hunk 3]
```diff
@@ -24,19 +24,19 @@
...
             + PREFIX_TASKNAME + "TASKNAME "
             + PREFIX_DATETIME + "DATETIME [, ENDDATETIME]"
-            + PREFIX_TAG + "TAG "
-            + PREFIX_LINK + "LINK "
-            + PREFIX_RECURRING + "PERIOD RECURRENCE\n"
+            + " [" + PREFIX_TAG + "TAG] "
+            + " [" + PREFIX_LINK + "LINK] "
+            + " [" + PREFIX_RECURRING + "PERIOD RECURRENCE]\n"
             + "Example: " + "addt" + " "
             + PREFIX_TASKNAME + "John Doe "
```
Comment (junjunjieOng) [inline src/main/java/seedu/address/logic/commands/AddTaskCommand.java:35]: Probably can change the Task name example to "Conduct Lecture" instead of "John Doe" to prevent confusion?

File: src/main/java/seedu/address/logic/commands/EditTaskCommand.java [hunk 4]
```diff
@@ -43,7 +42,7 @@
             + PREFIX_TAG + "Homework";
```
Comment (junjunjieOng) [inline src/main/java/seedu/address/logic/commands/EditTaskCommand.java:42]: Should we change the example to fit better to the profs?😅 Maybe "Do schoolwork CS2103T"?

File: src/main/java/seedu/address/logic/commands/AddTaskCommand.java (hunk 1 above)
Comment (snss231) [reply src/main/java/seedu/address/logic/commands/AddTaskCommand.java:38]: 👌

File: src/main/java/seedu/address/logic/commands/ViewCommand.java (hunk 2 above)
Comment (snss231) [reply src/main/java/seedu/address/logic/commands/ViewCommand.java:21]: 👌

File: src/main/java/seedu/address/logic/commands/EditTaskCommand.java (hunk 4 above)
Comment (snss231) [reply src/main/java/seedu/address/logic/commands/EditTaskCommand.java:42]: 👌

File: src/main/java/seedu/address/logic/commands/AddTaskCommand.java (hunk 3 above)
Comment (snss231) [reply src/main/java/seedu/address/logic/commands/AddTaskCommand.java:35]: 👌
